In [1]:
import numpy as np

#### Exercise 4
1. create a null vector / 1D array of size 10 and update fifth index to 11.

In [2]:
# create a null vector / 1D array of size 10
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
x[5] = 11
x

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays


In [4]:
# y = np.array([[1,2,3], [4,5,6]])
y = np.zeros((2,3))
y

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
y = y.reshape(3,2)
y

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
![](image/lat1.png)

In [6]:
z = np.ones((5,5))
print('Original array:', z, sep='\n')

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
z[1:4, 1:4] = 0
print('1 on the border and 0 inside in the array:', z, sep='\n')

1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


4. Take a look at the following matrix. Access the [2,1,1]

In [8]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [9]:
z[2,1,1]

2

#### ASSIGNMENT
1. Create a 4x4 matrix with values ranging from 0 to 3.\
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [10]:
assign1 = np.random.randint(0, 4, (4,4))
assign1

array([[1, 0, 3, 2],
       [2, 0, 1, 2],
       [2, 3, 3, 0],
       [2, 3, 3, 0]])

2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.\
![](image/assignment.png)

In [11]:
assign2 = np.arange(0,16).reshape(4,4)
assign2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
assign2_split = np.hsplit(assign2, 2)
assign2_split

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]